amugofjava/anytime_podcast_player

lib/services/download/download_manager.dart
lib/services/download/mobile_download_service.dart
lib/ui/anytime_podcast_app.dart

This PR separates (extract out) a small "DownloadManager" interface from the currently MobileDownloadService.
This change allows embedding anytime inside other apps and use the same FlutterDownloader plugin, overcoming its singleton requirement.
In addition it enables using a different implementation of download service and tasks management.
This PR should not cause in any behavioural changes.

Extract out DownloadManager from download service.

---

lib/ui/anytime_podcast_app.dart

This PR adds an additional parameter to the `AnytimeHomePage` which allows to  control whether the top bar is visible or hidden.
This enables embedding the main view inside another app that uses different top bar.
The default behaviour remains as it is today (visible: true).

Allow controlling top bar visibility

---

lib/ui/podcast/podcast_details.dart

Podcast descriptions that contain html tags are now rendered properly. _There has been padding changes on neighboring widgets to combat Html() widgets internal padding._

Render html tags in podcast description

---

lib/ui/widgets/download_button_widget.dart
lib/ui/widgets/episode_tile.dart
lib/ui/widgets/play_pause_button_widget.dart

We've consulted with our designer and made minimal changes to make a more streamlined, consistent UI.
- The download & play buttons lineWidth and their icon size is reduced.
- Episode title is no longer bold.
- Episode description is now the same size with podcast description text. (It was larger)
- Delete, Show Notes and Mark Played text and icon size are reduced.

Use lighter text weight and slimmer icons on EpisodeTile

---

lib/ui/anytime_podcast_app.dart
lib/ui/podcast/now_playing.dart
lib/ui/podcast/player_position_controls.dart
lib/ui/podcast/player_transport_controls.dart
lib/ui/themes.dart
lib/ui/widgets/mini_player_widget.dart
lib/ui/widgets/play_pause_button_widget.dart
lib/ui/widgets/speed_selector_widget.dart
lib/ui/widgets/transport_controls.dart

Made several changes for theme customization purposes, they have no visual effect on the plugin itself.
- Replaced static colors with their theme counterparts
- Colors.orange -> theme.primaryColor & theme.buttonColor,
- Added a condition to prevent white on white color for Play/Pause icon,
- Play/Pause button on Now Playing uses primaryColor for background & white for iconColor except when primaryColor is also white, which default the iconColor to scaffoldBackgroundColor
- Added selectedItemColor and unselectedItemColor parameters to BottomNavigationBar,
- Mini Player widgets
- textTheme has changed to accentTextTheme,
- divider now uses dividerColor from theme,
- play button uses iconTheme.color instead of accentColor.

Theme Changes

---

lib/bloc/settings/settings_bloc.dart
lib/entities/app_settings.dart
lib/l10n/L.dart
lib/l10n/intl_de.arb
lib/l10n/intl_en.arb
lib/l10n/intl_messages.arb
lib/l10n/messages_de.dart
lib/l10n/messages_en.dart
lib/l10n/messages_messages.dart
lib/services/settings/mobile_settings_service.dart
lib/services/settings/settings_service.dart
lib/ui/podcast/player_transport_controls.dart
lib/ui/settings/settings.dart
lib/ui/widgets/transport_controls.dart

this PR introduces an `autoOpenNowPlaying` settings flag that allows the user to control the behaviour when the user plays an episode and showing automatically the "NowPlaying" view. This is useful for opening this view straight from search results instead of going back and press the mini player.
I didn't add the setting option to the UI, let me know if you would like that.

Implement settings to automatically maximize player.

---

lib/services/podcast/mobile_podcast_service.dart

This is a small fix that goes through the API layer to load chapters instead of directly invoking the implementation.

Load chapters via API.

---

lib/ui/anytime_podcast_app.dart

- unselectedItemColor is changed because using disabledColor caused inconsistencies with other disabled items, 
- Selected chapter color now gets it value from theme. Reverted this change after seeing https://github.com/amugofjava/anytime_podcast_player/commit/41ab6bdfac5e368a1d132b090d193fdd86f373f8

Minor theme tweaks

---

lib/ui/podcast/chapter_selector.dart
lib/ui/widgets/mini_player.dart

This PR contains mini player widgets that were overlooked on https://github.com/amugofjava/anytime_podcast_player/pull/14
- Mini player uses accentTextTheme and play pause uses iconTheme.color,
_These changes are for customization purposes only and they have no effect on plugins own theme._

Apply theme changes to mini player widget

---

lib/ui/anytime_podcast_app.dart
lib/ui/library/discovery.dart
lib/ui/library/discovery_results.dart
lib/ui/search/search.dart
lib/ui/search/search_bar.dart
lib/ui/widgets/podcast_list_with_search_bar.dart

If inlineSearch is enabled, search bar will be added to top of PodcastList of DiscoveryResults. _This feature will be disabled by default._
SearchBar will behave similarly to Search icon on app bar except the search term can now be passed to Search view.
Set autoFocus of search TextField in Search view to false when the search term is passed.

Add inlineSearch feature

---

lib/bloc/settings/settings_bloc.dart
lib/entities/app_settings.dart
lib/services/settings/mobile_settings_service.dart
lib/services/settings/settings_service.dart
lib/ui/podcast/podcast_details.dart

Since we have our own payment system integrated into the plugin via hooks, this raised the need to hide `FundingMenu` on `PodcastDetails` page. We believe the least intrusive way to go with this change was to add a `showFunding` flag to `AppSettings`.
This PR introduces `showFunding` settings flag that allows developers to hide `FundingMenu` on `PodcastDetails` page.
This setting is `true` by default and won't be configurable through `Settings` page.

Add Show Funding Menu settings to show/hide FundingMenu on PodcastDetails

---

lib/bloc/podcast/podcast_bloc.dart
lib/entities/feed.dart
lib/ui/podcast/podcast_details.dart

Add a minor convenience to the user, whenever the user opens the podcast detail it silently updates the list of episodes.
Based on this suggestion: https://github.com/breez/breezmobile/issues/456
https://user-images.githubusercontent.com/1225438/123450993-ab049a80-d5b3-11eb-8930-d92b04815276.mp4

Refresh the podcast on Podcast Details page creation

---

lib/ui/anytime_podcast_app.dart
lib/ui/podcast/funding_menu.dart
lib/ui/podcast/podcast_details.dart
lib/ui/podcast/transport_controls.dart
lib/ui/settings/settings.dart
lib/ui/widgets/episode_tile.dart
lib/ui/widgets/search_provider.dart
lib/ui/widgets/speed_selector.dart

Dialogs use root navigator by default. This causes issues when the plugin is opened through an app with it's own instance of Navigator. The dialogs should be pushed to the nearest Navigator from the context in this case.
For example:
- The plugin is embedded into an app,
- a dialog that belongs to the plugin is opened,
- calling Navigator.pop(context) to close the dialog would pop the last item on app's Navigator instead of popping the dialog.

Open dialogs without using root navigator

---

pubspec.yaml

Hi 👋
I had to try many Flutter SDK versions to find which is required on AnytimePodcast.
So, it could be useful to set it explicitly in the project setup.
Cheers

Fix required flutter version to 2.2.3.

---

lib/services/podcast/mobile_podcast_service.dart

I ran into an issue loading this RSS feed manually: http://adc.equalarea.com/feed/ - because this feed is missing a `<copyright>` tag, it cannot be loaded. This PR fixes this issue.
(Note that even with this fix, items from this feed cannot be successfully downloaded, because of an issue with two `<enclosure>` tags in a single item. That's an edge case that [isn't supported according to Apple's spec](https://podcasters.apple.com/support/823-podcast-requirements), but it should be a simple fix - let me know if you'd accept a PR to podcast_search to fix that issue, or if that's too weird a scenario to bother with the extra complexity.)

Display podcast even if missing title, description, or copyright tags

---

lib/ui/podcast/podcast_details.dart

Hopefully close #47 
I have used StreamController to trigger animation instead of SetState() because the parent widget was rebuilding the whole description Text widget instead of animating. 
I am open to suggestions if there is a better way to achieve this. Though I think this one isn't bad either.

add animation in podcast description button

---

lib/ui/library/opml_export.dart

Fixes #91
Error comes from context manipulation done
synchronously in `build` method.

OPML Export - throws error on iOS

---

lib/ui/anytime_podcast_app.dart

Fixes #68
Added a Material widget around Dialog TextField.
Useful on iOS, when using a CupertinoAlertDialog.

[iOS] Add manual RSS feed shows error

---

ios/Runner/Info.plist

Closes https://github.com/amugofjava/anytime_podcast_player/issues/62
This is simple fix allowing all HTTP (non secured) connections on iOS. 
There is[ another approach](https://github.com/amugofjava/anytime_podcast_player/pull/69) disable HTTP connections, and attempting to replace all `http://` by `https://`

Accept all HTTP connections on iOS.

---

lib/bloc/podcast/episode_bloc.dart

Fixes #86 
Seems like episodeIndex check in listener was not correct. If episode not found in current downloads list then it should be -1 and Refetch download list.
I changed the condition but not sure if it was necessary for other functionality in the application.
Now it checks if the episode is not present and download is completed only then Refetch download list.

fix auto download refresh
